import Data.Char

main = do
  ls <- fmap (map words . lines) $ readFile "bootstrap/translit.txt"
  writeFile "www/js/translit.js" 
       (unlines ("// This script is automatically generated by bootstrap/mktranslit.hs":
                 "":
                 "const translit = new Map();":
                 concatMap append ls ++
                 [""
                 ,"function transliterate(s) {"
                 ,"   let s1 = s.normalize(\"NFD\");"
                 ,"   let s2 = \"\";"
                 ,"   for (const c of s1) {"
                 ,"       let c2 = translit.get(c);"
                 ,"       s2 += (c2 != null) ? c2 : c;"
                 ,"   }"
                 ,"   if (s1 == s2)"
                 ,"      s2 = s;   // return the original non-normalized text"
                 ,"   return s2;"
                 ,"}"]))

append [[c],s] =
  ("translit.set(\""++[c]++"\",\""++s++"\");") :
  if c /= toUpper c
    then ["translit.set(\""++[toUpper c]++"\",\""++toUpperFirst s++"\");"]
    else []
  where
    toUpperFirst (c:cs) = toUpper c : cs
    toUpperFirst s      = s
append [[c]] =
  ("translit.set(\""++[c]++"\",\"\");") :
  if c /= toUpper c
    then ["translit.set(\""++[toUpper c]++"\",\"\");"]
    else []
  where
    toUpperFirst (c:cs) = toUpper c : cs
    toUpperFirst s      = s
