import Data.Char

main = do
  ls <- fmap (map words . lines) $ readFile "bootstrap/translit.txt"
  writeFile "www/js/translit.js" 
       (unlines ("// This script is automatically generated by bootstrap/mktranslit.hs":
                 "":
                 "const translit = new Map();":
                 concatMap append ls ++
                 [""
                 ,"function transliterate(s) {"
                 ,"   var s2 = \"\";"
                 ,"   for (const c of s) {"
                 ,"       s2 += (translit.get(c) || c);"
                 ,"   }"
                 ,"   return s2;"
                 ,"}"]))

append [[c],s] =
  ("translit.set(\""++[c]++"\",\""++s++"\");") :
  if c /= toUpper c
    then ["translit.set(\""++[toUpper c]++"\",\""++toUpperFirst s++"\");"]
    else []
  where
    toUpperFirst (c:cs) = toUpper c : cs
    toUpperFirst s      = s
